### PR TITLE
Rfid and timer

### PR DESCRIPTION
**Pull request by chris1howell**
Merge Request for RFID into Master

### CODE REVIEW

**Comment by Olverine** [comment]
We are currently developing this feature for firmware version 3.3.2 and applying the changes we make to this PR every once in a while. It is however very difficult to test the code and confirm that it is working for the reasons stated in #169.

**Comment by jeremypoulter** [comment]
Thanks, really appreciate it, maybe we can get it merged in to the v3 branch as a first step, but may very well have to break comparability when merged to v4

**Comment by jeremypoulter** [comment]
@Olverine v4 is getting more mature now, are you interested in continuing with this PR?

**Comment by chris1howell** [comment]
@jeremypoulter I just spoke with @matth-x, he is going to work on this PR and integrate RFID with standalone functionality and OCPP.

**Comment by jeremypoulter** [comment]
Superseded by #325

**Pull request closed without merging**
