### PR TITLE
OCPP: integration of further functions

### PR DESCRIPTION
**Pull request by matth-x**

### CODE REVIEW

**Comment by matth-x** [comment]
Thank you Jeremy! Then I can integrate it next week right away.

**Comment by matth-x** [comment]
Should be ready now. Soft reset and FW update are integrated now as well.

**Comment by chris1howell** [comment]
Did this PR also include the heartbeat fix?

**Comment by matth-x** [comment]
Yes, both the WebSocket and OCPP heartbeat work, I've checked them. Probably the issue was that my library was ignoring the OCPP heartbeat interval when it was set with the BootNotification. I have already solved that. But I am not 100% sure if that was the actual reason.

**Pull request merged**
