### PR TITLE
delete static files if there's a gui build

### PR DESCRIPTION
**Pull request by KipK**
clean-up web_server_static_files.h when building firmware and the ui build dir is not empty

### CODE REVIEW

**Comment by jeremypoulter** [comment]
Why is this needed? `web_server_static_files.h` is regenerated on build, is it not?

**Comment by KipK** [comment]
not really, the #includes where appened to the file, so we have to clean it manually first before commiting or we will have thousands of includes after few gui revision ( because of the hash in the file names  )

**Comment by jeremypoulter** [comment]
No I just checked, `web_server_static_files.h` is deffinatly generated from scratch when needed, <https://github.com/OpenEVSE/ESP32_WiFi_V4.x/blob/638dc90257b477966b6dd6305a52653b40acb149/scripts/extra_script.py#L109>, the problem you are seeing is because the files are still in the dist dir. We either need to remove the hash from the file name and/or clean out the dist dir before building.

**Comment by KipK** [comment]
I've updated, it nows delete .h statics if there's a gui build

**Comment by jeremypoulter** [comment]
I think it is more the dist dir in the GUI you need to clear, then selectively delete the header files that don't exist in the web static directory. If you delete all the header files they will have to be generated every build.

**Comment by KipK** [comment]
It only deletes the headers if the dist dir is not empty. Building the gui always clears the dist dir.
If we delete the files at the fw build process I don't get how it can work ?

**Comment by jeremypoulter** [comment]
@KipK did you mean to close?

**Comment by KipK** [comment]
nope I have forced pushe the static file update to this branch, forgot this branch was for this pull request. 
Will have to redo somehow as it's all lost

**Pull request closed without merging**
