### PR TITLE
do not set Scheduler claim if evse module communication is not ready

### LINKED ISSUE #517: Timer set charge_current claim with 0 amp
I see Timer is setting a charge_current claim with getMaxHardwareCurrent() if EVSE is active when timer going to active.
But mose of the Time the claim is posted with "0" as max_current , so pilot is locked at 6A )
It looks like    properties.setChargeCurrent(_evse->getMaxHardwareCurrent()); gives 0 for whatever reason;

This is part of code in scheduler.cpp:
    ``` if(EvseState::Active == currentEvent.getState())
      {
        priority = EvseManager_Priority_Timer;
        properties.setChargeCurrent(_evse->getMaxHardwareCurrent());
      }
      _evse->claim(EvseClient_OpenEVSE_Schedule, priority, properties);```

I'm publishing getMaxHardwareCurrent() in /status to follow it, but it's always at 32A, I don't get why this part of code fails on scheduler.cpp

To reproduce:

- Set a timer to have OpenEvse Active at this time, reboot wifi module, at boot it will publish a timer claim with charge_current at 0.
ps: I have also tryied replacing getMaxHardwareCurrent() by getMaxConfiguredCurrent() and getMaxCurrent() and same thing happend

### PR DESCRIPTION
**Pull request by KipK**
fix #517

### CODE REVIEW

**Comment by KipK** [comment]
I displays the claims/target in a tab in the UI, to keep it clear for users I'd rather have ok values than hardcoded ones displayed.

This issue probably hide some others.  I temporise on scheduler, but it's probably on the evseManager side that things should be handled isn't it ?

**Comment by KipK** [comment]
@jeremypoulter I think we are close to solve many other issues as #452 , seeing my latest comment here https://github.com/OpenEVSE/ESP32_WiFi_V4.x/issues/517#issuecomment-1384523287

If it's the case this PR has no reason te be merged and we should investigate on evse_manager

**Comment by jeremypoulter** [comment]
I think the correct way to solve this would befor the scheduler (and all the other modules) to wait for the evse to be active before sending the claims... but that being said the EVSE managershould also handle the claims at any point. 

IMHO setting to a fixed value is not a problem, 80A is the maximum allowed by the spec so not just a random value, and after startup will get reset. potentially I could hide this in the web layer or EVSE layer. but for this issue specifically I think it is a better fix than polling until the value is read correctly.

I will also check on why 0 is returned under certain conditions, if that is just the default before the correct value is read then again 80 is as good as 0 (well probably better)

**Comment by jeremypoulter** [comment]
Yeah I think it is just a startup timing issue, I think setting the defailt valueto 80 would work: 
https://github.com/OpenEVSE/ESP32_WiFi_V4.x/blob/master/src/evse_monitor.cpp#L164-L167 probably should be

```c++
  _min_current(6),
  _pilot(6),
  _max_configured_current(80),
  _max_hardware_current(80),
```

After the EVSE starts up the claims will be re-evaluated and the value will be clamped (or at least it should be)

**Comment by KipK** [comment]
> I think the correct way to solve this would befor the scheduler (and all the other modules) to wait for the evse to be active before sending the claims... but that being said the EVSE managershould also handle the claims at any point.

Yeah this would imply patching all the services, and deserve evseManager purpose no ? 
I'd rather go for fixing evsemanager evaluateClaim and let it handle that

**Review by jeremypoulter — APPROVED** [review]

**Comment by KipK** [comment]
There's still something strange, I can see the claim not being reevaluated sometime. It stays at 80.

**Pull request merged**
