### PR TITLE
Various Time zone fixes

### LINKED ISSUE #107: Timezone Issues
Selecting `Europe/London` timezone and NTP results in the correct time being set on the WiFi interface and on the controller :+1: 

IMG_0154

However, selecting `GMT+1` which should be same, results in the correct time being displayed on the WiFi interface, however the controller is 2hrs behind :-1: 

Could a solution just be to remove the GMT+X timezones? Since these seem to be a duplicate of the `Continent/City` timezones.  

IMG_0153

Thanks to Bill for reporting on the forum:https://community.openenergymonitor.org/t/can-openevse-default-be-set-to-eco-mode/11278/14
***

I've also noticed that the timezone dropdown menu does not work on iOS, tested on both iOS Chrome and iOS Safari on an ipad mini:

IMG_0152

### PR DESCRIPTION
**Pull request by jeremypoulter**
- Set the default time zone to the defined one
- skip `|` when setting the env var, stops the timezone from being recognised
- Filter out the Etc/... time zones

Fixes #107

### CODE REVIEW

**Comment by KipK** [comment]
perfect, it solves the timer bug, and it probably fix #467 I have to check that later

**Comment by KipK** [comment]
One should push a new release after this merge.  4.1.7 has too much problems. This was the last urgent one to fix.

**Comment by KipK** [comment]
now this fix #467  :+1

**Comment by jeremypoulter** [comment]
At the moment it forces UTC in the code, so it doesn't matter what time zone you send. I am going to look at setting the time zone for manual set times as the DST info from the timezone is handy. Also need to figure out how to handle a different timezone of the EVSE and the browser. The ESP now sends the local and GMT times (according to the ESP) but this is then displayed in the timezone of the browser by default. Not sure if that is much of an issue other than for testing.

**Comment by KipK** [comment]
strage, because if i send to /settime 
ntp: false
tz: Europe/Paris|CET-1CEST,M3.5.0,M10.5.0/3
time: 2023-03-13T08:55:00.000+01:00

It then has 
local_time: "2023-03-13T08:55:00+0000"
time: "2023-03-13T08:55:00Z"

**Comment by KipK** [comment]
corrected I sent it wrong, but same problem:

ntp: false
tz: Europe/Paris|CET-1CEST,M3.5.0,M10.5.0/3
time: 2023-03-13T09:19:33.023+01:00

gives:
local_time: "2023-03-13T09:19:33+0000"
time: "**2023-03-13T09:19:33Z"**

**Comment by jeremypoulter** [comment]
Yeah, I think I need to update it to properly handle timezones for manual mode.... :) <https://youtu.be/-5wpm-gesOY>

**Comment by KipK** [comment]
ahahah that's insane reality we have to deal with :)))

**Comment by KipK** [comment]
Can it be merged yet? Even if you change the manual tz later, it already works ok

**Comment by jeremypoulter** [comment]
Found many more timezone bugs, and fixed most of them, but this is still WIP

**Comment by jeremypoulter** [comment]
I think the main task left is to work out how to set the time manually in the EVSE's timezone

**Comment by KipK** [comment]
I've updated the UI2 for new /limit. 

Works ok for manual without tricking to UTC.
UI sends time as UTC + timezone and we're getting back correct local time

**Comment by KipK** [comment]
all good here. Thanks for this

**Comment by KipK** [comment]
@glynhudson can you merge this one ?

**Pull request merged**
