### PR TITLE
Fix for broken EmonCMS updates

### LINKED ISSUE #404: Error from emoncms
I'm running the latest development release. The "Energy Monitoring" area in OpenEVSE says it's not connected.   I have an error coming back from emoncms when data is sent to it.   Here is what I see in the OpenEVSE serial console debug:

`{"amp":0,"voltage":244.9400024,"pilot":6,"wh":2017162,"session_energy":0.258333333,"total_energy":2017.162,"temp":300,"temp_max":300,"temp1":false,"temp2":300,"temp3":false,"temp4":495,"state":254,"flags":1280,"vehicle":1,"colour":6,"manual_override":0,"override":"{\"state\":\"null\"}","freeram":163232,"divertmode":1,"srssi":-71}
{"emoncms_connected":0,"emoncms_message":"Input in not a valid JSON object"}`

I would expect the error is caused by this: `"override":"{\"state\":\"null\"}"`

### PR DESCRIPTION
**Pull request by jeremypoulter**
The new MQTT updates sent the override JSON in the regular updates to EmonCMS and EmonCMS can not handle this soremoved. I think this is not needed as it is handled directly in the MQTT module now.

Fixes #404

### CODE REVIEW

**Comment by jeremypoulter** [comment]
@KipK Can you check this, I don't think that code was needed, but if it is I can add a filter on the data we send to EmonCMS

**Comment by KipK** [comment]
> @KipK Can you check this, I don't think that code was needed, but if it is I can add a filter on the data we send to EmonCMS

I have to check, but I think it's there in case manual override is activated from another channel than mqtt. To get the feedback.
It could be changed in override function to push it when an override is called then.

But can't emoncms ignore unneeded topics ( or better follow new api  ? As you will also have this problm for /claims /schedule and all other fields we've added.

**Comment by jeremypoulter** [comment]
That was my original thinking, but this seemed like the easier fix... You are right about the manual override being triggered from different sources as well as the claims and schedule. It is probably better to drive the MQTT update from those modules directly so the MQTT topics are updated when the data changes.

**Comment by KipK** [comment]
> It is probably better to drive the MQTT update from those modules directly so the MQTT topics are updated when the data changes.

I can do that. Unfortunately, this will prevent us to profit of those new events in a new UI then.

**Comment by jeremypoulter** [comment]
For the UI I have been adding version numbers of the different resources to the status. When these change the UI goes and fetches the appropriate response. Seemed like the best way to do it without exposing all the resources via the status, really need to change the Websocket protocol to be something a bit more flexible

**Comment by jeremypoulter** [comment]
But I can look at the updates as part of this ticket.

**Comment by KipK** [comment]
Just to be clear, I add the getoverride() to manual.cpp and add an mqtt push ( also in manual.cpp ) of this event only when override change ( no evevnt_send() ? )

**Comment by jeremypoulter** [comment]
@glynhudson let me look at the few cases @KipK has mentioned

**Comment by KipK** [comment]
I've made a new PR for this without loosing override change from different channels.
https://github.com/OpenEVSE/ESP32_WiFi_V4.x/pull/416

**Comment by jeremypoulter** [comment]
Superseded by #416

**Pull request closed without merging**
