### PR TITLE
Fix#411

### PR DESCRIPTION
**Pull request by KipK**
This should fix #411

Depends of https://github.com/OpenEVSE/ESP32_WiFi_V4.x/pull/412 first

### CODE REVIEW

**Comment by jeremypoulter** [comment]
Thanks for the contribution, will give it a test

**Comment by glynhudson** [comment]
I can confirm the fix works for me. Happy for this to be merged.

**Comment by glynhudson** [comment]
@jeremypoulter can this be merged?

**Comment by jeremypoulter** [comment]
Looks good to me, @KipK please sync with `master` then can be merged

**Review by jeremypoulter — APPROVED** [review]

**Pull request merged**
