### PR TITLE
Add some events through websocket & mqtt

### PR DESCRIPTION
**Pull request by KipK**
discussed here https://github.com/OpenEVSE/ESP32_WiFi_V4.x/issues/401#issuecomment-1279959862

Add missing events over web socket / mqtt
Send full status data over web socket when new client connect
fix Pilot event bug

### CODE REVIEW

**Comment by KipK** [comment]
Do not commit yet. I have to test this first

**Comment by KipK** [comment]
ok all good to me.

It push over websocket / mqtt amp/voltage when charging each sec like for the lcd 
push charge session data at state change ( + amp to get a fast 0A when disabling )

**Comment by KipK** [comment]
Also added a fix for a little bug with Pilot I have spotted . It was hidden in the middle of all the /status poll traffic

**Comment by KipK** [comment]
Damn I've messed the rebase again.... refixing....

**Comment by KipK** [comment]
When this will be merge, we will be able to remove the /status polling on actual UI too.

**Comment by KipK** [comment]
No it's ok. But I can resubmit a proper rebased pull request if you want. 
Also I wonder if I can add the whole API over websocket. This would makes sense.

**Comment by KipK** [comment]
I'm closing & resubmit

**Review by jeremypoulter — APPROVED** [review]
Changes look good to me

**Pull request merged**
