### PR TITLE
Issue #187 - Feed watchdog in http_update_write()

### LINKED ISSUE #187: HTTP update failes on ESP32 Etherent gateway
Testing trying to update from 3.3.2 to 4.0.1 

Selection_436
Selection_435

### PR DESCRIPTION
**Pull request by ianrrees**
I've only spent a couple minutes testing this on an ESP32-PoE-ISO board, but it seems to work, and it compiles OK for the targets on the releases page.

Fixes #187

### CODE REVIEW

**Comment by jeremypoulter** [comment]
Thanks for the contribution, I will check it out

**Comment by ianrrees** [comment]
Thank you for identifying the problem!  I'm hoping to look at upgrading Mongoose this weekend.

There is something strange going on with the relationship between WiFi and Ethernet that I don't fully understand yet.  I think maybe the issue is if the WiFi is connected, and ethernet too, sometimes things get in to a bad state - I've just been erasing the whole flash to nuke the saved WiFi info.  Probably not worth digging too deep before a big networking change anyway.

**Comment by ianrrees** [comment]
Also, just to be clear, I don't think this really fixes the underlying problem - it's just a hacky fix for that one symptom.  Really, the networking stuff shouldn't block the main loop for so long.  Haven't had a chance to look at the current version of Mongoose yet, but perhaps it provides a nice way to resolve that issue.  Or, I believe the ESP32 Arduino framework is actually running FreeRTOS under the hood, it might be more effective to have the OS handle the lower-level networking stuff.

**Comment by jeremypoulter** [comment]
Looks to work well.

**Review by jeremypoulter — APPROVED** [review]

**Pull request merged**
