### PR TITLE
Platform IO ESP32 core 4.4

### LINKED ISSUE #353: Update to latest ESP32 Core
Update to a newer / latest version of the ESP32 core

### PR DESCRIPTION
**Pull request by jeremypoulter**
Uplift to the latest ESP32 Platform IO core, including ESP IDF 4, this has a lot better debug features, mainly builtin stack trace decoding. 

Fixes #353

### CODE REVIEW

**Comment by jeremypoulter** [comment]
Currently this builds, but is crashing somewhere in the mongoose library...

**Comment by ruimarinho** [comment]
@jeremypoulter I'm getting an error compiling with espressif32@1.11.1 which I believe to be related with Apple Silicon and most likely fixed on newer version of this package or its dependencies 

```
~/.platformio/packages/toolchain-xtensa32@2.50200.97/bin/../lib/gcc/xtensa-esp32-elf/5.2.0/../../../../xtensa-esp32-elf/bin/ld: cannot open linker script file esp32.project.ld: No such file or directory
collect2: error: ld returned 1 exit status
*** [.pio/build/openevse_nodemcu-32s/firmware.elf] Error 1
```

Any chance of getting this PR merged using the latest version of `espressif32`?

**Comment by jeremypoulter** [comment]
I believe it still needs some work, I think it was triggering the watchdog, so need to figure that out first

**Comment by ruimarinho** [comment]
There are a ton of fixes related to WiFi's performance I'm eager to test this bump :) (probably [4.3.2](https://github.com/espressif/esp-idf/releases/tag/v4.3.2) since it's out now).

**Comment by jeremypoulter** [comment]
Have removed the building via IDF and gone back to vanilla Arduino builds for now, building Arduino as a component is a little unreliable and the latest Arduino looks to support DHCP/DNS fine

**Comment by jeremypoulter** [comment]
Did also require fixes to ArduinoOcpp so dependant on #325

**Comment by matth-x** [comment]
@jeremypoulter `matth-x/ArduinoOcpp@0.1.0` is now on the registry with the `#include`s issue fixed

**Comment by jeremypoulter** [comment]
@glynhudson  think this is good to go, can you take a look?

**Comment by jeremypoulter** [comment]
Actually, ignore that there are several new versions of the core since I started this, will take a look.

**Comment by jeremypoulter** [comment]
ESPHome and WLED to name a few are still using 3.5 of the ESP 32 core and given the GitHub workflows now look to be broken probably best to get this merged then look at uplifting again to (now) 4.4

**Comment by KipK** [comment]
yes please merge :) those new debugging features are essential ( plus some wifi/bt security fixes taht are not backported )

**Comment by glynhudson** [comment]
Nice work. I've just tested with WiFi V1 hardware and I'm getting "OpenEVSE not responding or not connected" error. There seems to be no connection between the WiFi module and controller and no response via RAPI:

```
$SV 233370^07
$GV^35
$SV 233130^01
$SV 233670^02
$GV^35
$SV 233330^03
$SV 234170^02
$GV^35
$SV 233890^02
$SV 234140^01
$GV^35
$SV 233430^04
```

**Comment by glynhudson** [comment]
Have you been able to replicate this issue on a OpenEVSE WiFi V1 module?

**Comment by KipK** [comment]
> Have you been able to replicate this issue on a OpenEVSE WiFi V1 module?

not on my side. I have no such problem here. Using my branch based on this one.

**Comment by jeremypoulter** [comment]
@glynhudson I have been able to reproduce the issue, looks to be specific to the OpenEVSE WiFi module. The RAPI is being sent but the ESP is not reading any serial data back for some reason. Probably a configuration issue.

**Comment by jeremypoulter** [comment]
@glynhudson think I have resolved the issue, give it a go now

**Comment by glynhudson** [comment]
Great, it's working now on OpenEVSE V1 hardware. Nice work.

**Pull request merged**
