### PR TITLE
add upload_progress event to websocket

### PR DESCRIPTION
**Pull request by KipK**
This send "upload_progress" value to websocket while uploading
It gives better upload file progress bar as it seems to be broken using classic progress event from xmlhttprequest ( also can't work correctly behind proxy ) 

I'm using it on wip UI , demo at the end of video here https://watch.screencastify.com/v/EP73NnuERNFHosoQAR92

### CODE REVIEW

**Comment by jeremypoulter** [comment]
Interesting, the current upload progress should not be effected by a proxy, should be based on the progress of the upload from the browser POV, IE how much has been sent. That being said doing it this way will also include the local processing  as well so no problem with it

**Comment by KipK** [comment]
> Interesting, the current upload progress should not be effected by a proxy, should be based on the progress of the upload from the browser POV, IE how much has been sent. That being said doing it this way will also include the local processing as well so no problem with it

Seems in some case, the browser send  big chunks of file quickly to the proxy.
progress value is jumping to 100% in no time on browser side, while proxy is slowingly finishing the task.
This is the case with some node.js proxying like  Vite use.

**Comment by jeremypoulter** [comment]
Ah that makes sense the changes look reasonable, will test and merge.

**Review by jeremypoulter — APPROVED** [review]

**Comment by KipK** [comment]
Please do not merge yet, I'll rename it to ota_progress, and also had an "ota" event for "started" "success" "fail" "error" status

**Comment by KipK** [comment]
It's ok now.

**Review by jeremypoulter — APPROVED** [review]

**Pull request merged**
